export interface ILlmProvider {
  generate(prompt: string): Promise<string>;
  describe?(): string;
}

export class MockLlmProvider implements ILlmProvider {
  constructor(private readonly response?: string) {}

  describe(): string {
    return "provider=mock | model=built-in-mock";
  }

  async generate(prompt: string): Promise<string> {
    if (this.response) {
      return this.response;
    }

    if (isDraftPrompt(prompt)) {
      return JSON.stringify({
        markdown: "## Mock PR Review Draft\n\n- This draft is generated by MockLlmProvider.\n- Switch off `prReviewer.llm.useMock` to use Copilot."
      });
    }

    if (isScorePrompt(prompt)) {
      return JSON.stringify({
        overallScore: 78,
        scoreBreakdown: [
          { dimension: "Correctness", score: 80, rationale: "Mock: correctness looks acceptable." },
          { dimension: "Maintainability", score: 76, rationale: "Mock: maintainability has moderate risk." },
          { dimension: "Reliability", score: 79, rationale: "Mock: reliability appears stable." },
          { dimension: "Security", score: 75, rationale: "Mock: security checks need manual verification." },
          { dimension: "Performance", score: 77, rationale: "Mock: performance impact seems limited." },
          { dimension: "Test Quality", score: 78, rationale: "Mock: tests look partially covered." },
          { dimension: "Traceability", score: 81, rationale: "Mock: traceability links are available." }
        ],
        evidence: [{ snippet: "mock-evidence" }],
        confidence: "medium"
      });
    }

    return JSON.stringify({ markdown: "## Mock Draft" });
  }
}

function isScorePrompt(prompt: string): boolean {
  return prompt.includes('"overallScore"') && prompt.includes('"scoreBreakdown"') && prompt.includes('"confidence"');
}

function isDraftPrompt(prompt: string): boolean {
  return prompt.includes('"markdown"') && prompt.includes("Generate a PR review markdown draft");
}
