import { Stage1ReviewOrchestrator } from "../src/orchestrator/reviewOrchestrator.js";
import { MockConfluenceProvider } from "../src/providers/mocks/mockConfluenceProvider.js";
import { MockGithubProvider } from "../src/providers/mocks/mockGithubProvider.js";
import { MockJiraProvider } from "../src/providers/mocks/mockJiraProvider.js";

const githubProvider = new MockGithubProvider({
  "acme/platform#42": {
    metadata: {
      title: "PROJ-123 Add retry policy",
      body: "Improve callback reliability",
      author: "alice",
      baseBranch: "main",
      headBranch: "feature/retry",
      url: "https://github.com/acme/platform/pull/42"
    },
    files: [
      { path: "src/retry.ts", patch: "+ export const retry = true;" },
      { path: "tests/retry.test.ts", patch: "+ it('retries', () => {})" }
    ],
    commits: [
      { sha: "1", message: "PROJ-123 add retry logic" },
      { sha: "2", message: "PROJ-124 improve timeout handling" }
    ],
    checks: [{ name: "unit-tests", status: "completed", conclusion: "success" }],
    comments: []
  }
});

const jiraProvider = new MockJiraProvider([
  {
    key: "PROJ-123",
    summary: "Retry policy for callback",
    description: "Add bounded retry policy",
    acceptanceCriteria: ["Retries <= 3"],
    nfr: ["No P99 increase"],
    risks: ["Duplicate callback risk"],
    testingRequirements: ["Retry unit tests"],
    links: ["https://example.atlassian.net/wiki/spaces/ENG/pages/101"]
  },
  {
    key: "PROJ-124",
    summary: "Timeout handling",
    description: "Tune timeout fallback",
    acceptanceCriteria: ["Fallback on timeout"],
    nfr: ["No memory leak"],
    risks: ["Aggressive timeout"],
    testingRequirements: ["Timeout integration test"],
    links: ["https://example.atlassian.net/wiki/spaces/ENG/pages/102"]
  }
]);

const confluenceProvider = new MockConfluenceProvider({
  byUrl: {
    "https://example.atlassian.net/wiki/spaces/ENG/pages/101": {
      id: "101",
      title: "PROJ-123 Retry Design",
      url: "https://example.atlassian.net/wiki/spaces/ENG/pages/101",
      content: "Scope, API contract, rollback, monitoring"
    }
  },
  byQuery: {
    retry: [
      {
        id: "205",
        title: "Retry Monitoring Runbook",
        url: "https://example.atlassian.net/wiki/spaces/SRE/pages/205",
        content: "Monitoring and incident actions"
      }
    ]
  }
});

const llmProvider = {
  async generate(prompt: string) {
    if (prompt.includes("Generate a PR review markdown draft")) {
      return JSON.stringify({
        markdown: "## PR Review Draft\n\n- generated by mock llm in demo"
      });
    }
    return JSON.stringify({
      overallScore: 82,
      scoreBreakdown: [
        { dimension: "Correctness", score: 84, rationale: "ok" },
        { dimension: "Maintainability", score: 81, rationale: "ok" },
        { dimension: "Reliability", score: 83, rationale: "ok" },
        { dimension: "Security", score: 80, rationale: "ok" },
        { dimension: "Performance", score: 79, rationale: "ok" },
        { dimension: "Test Quality", score: 86, rationale: "ok" },
        { dimension: "Traceability", score: 82, rationale: "ok" }
      ],
      evidence: [{ snippet: "demo evidence" }],
      confidence: "high"
    });
  }
};

const orchestrator = new Stage1ReviewOrchestrator({
  githubProvider,
  jiraProvider,
  confluenceProvider,
  llmProvider
});

const result = await orchestrator.run({
  prLink: "https://github.com/acme/platform/pull/42",
  reviewProfile: "default"
});

console.log(JSON.stringify(result, null, 2));
